### PR TITLE
(RK-223) Allow Puppetfile Git content to track environment branch name.

### PR DESCRIPTION
**Pull request by scotje**

### CODE REVIEW

**Comment by scotje** [comment]
Going to add some additional spec tests tomorrow morning.

**Comment by scotje** [comment]
OK, I think the unit test coverage is all in place now.

**Comment by scotje** [comment]
Updated the Puppetfile docs.

**Comment by scotje** [comment]
Rebased with string externalization stuff.

**Comment by andersonmills** [comment]
:+1:

YEEHAW!

**Pull request merged**
