### PR TITLE
(RK-327) Fix CRI and Ruby related issues from 3.0.0 release

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by Magisus** [comment]
We should also update the `required_ruby_version` in the gemspec.

**Comment by justinstoller** [comment]
Good catch, updated.

**Comment by Magisus** [comment]
We should probably also update Travis to not test on older Ruby versions on this branch.

**Review by Magisus — APPROVED** [review]

**Comment by Magisus** [comment]
Are we going to do the changelog update as a separate PR or do you want to lump it in here?

**Comment by justinstoller** [comment]
If we're good with these changes then I'll update the CHANGELOG in this PR and we can get this out to folks.

**Comment by Magisus** [comment]
I built a gem with this, tried installing it on Ruby 2.1.9, failed:
```
➜  r10k git:(rk326) ✗ rbenv global 2.1.9
➜  r10k git:(rk326) ✗ gem install r10k-3.0.0.gem
Fetching: colored-1.2.gem (100%)
Successfully installed colored-1.2
Fetching: cri-2.15.1.gem (100%)
ERROR:  Error installing r10k-3.0.0.gem:
	cri requires Ruby version ~> 2.3.
```

Then on Ruby 2.5.1:
```
➜  r10k git:(rk326) ✗ rbenv global 2.5.1
➜  r10k git:(rk326) ✗ gem install r10k-3.0.0.gem
...
➜  r10k git:(rk326) ✗ r10k version
r10k 3.0.0
➜  r10k git:(rk326) ✗ r10k --help
NAME
    r10k - Killer robot powered Puppet environment deployment
...
```
Seems right to me.

**Pull request merged**
