### PR TITLE
(RK-143) Handle spaces in arguments when executing windows commands

### PR DESCRIPTION
**Pull request by adrienthebo**
This pull request updates the Open3.capture3 call to pass an argument vector to avoid issues with spaces in commands on Windows, adds test coverage to the runner, and fixes some bugs that were uncovered by the added spec coverage.

### CODE REVIEW

**Comment by adrienthebo** [comment]
@lmayorga1980 this is a cleaner fix of #455 and fixes some other issues uncovered during testing, could you test this fix out?

**Comment by lmayorga1980** [comment]
Sure. Will do it tonight

**Comment by adrienthebo** [comment]
Thanks!

**Comment by lmayorga1980** [comment]
@adrienthebo cloned as `git clone -b bugfix/master/rk-143-quote-windows-command-args  git@github.com:adrienthebo/r10k.git`

I am guessing that the issues still exist 

```
ERROR    -> Command exited with non-zero exit code:
09:41:22            Command: git --git-dir C:/Program Files/OpenSSH/home/_puppet/.r10k/git/https---github.com-chocolatey-puppet-chocolatey.git fetch --prune
09:41:22            Stderr:
09:41:22            fatal: unable to access 'https://github.com/chocolatey/puppet-chocolatey.git/': transfer closed with outstanding read data remaining
09:41:22            Exit code: 128
```

**Comment by adrienthebo** [comment]
@lmayorga1980 that error looks like an issue with the connection, and not whether the command was properly quoted. Given that the transfer was able to start at all, my guess would be that the arguments were parsed correctly and spaces were properly escaped but GitHub hiccuped while running the clone. Did you try running the command again after this failure or did you just test this once?

**Comment by adrienthebo** [comment]
@lmayorga1980 it's been a few days since my last comment, and I wanted to follow up - the error that you're seeing looks like it's unrelated to the actual command parsing and execution inside of r10k and looks like it happened due to a network issue with Git, were you able to confirm that the error regularly occurs?

**Comment by lmayorga1980** [comment]
Going to check this soon.

**Comment by lmayorga1980** [comment]
@adrienthebo 

it works with the branch `git clone -b bugfix/master/rk-143-quote-windows-command-args  git@github.com:adrienthebo/r10k.git`

**Comment by adrienthebo** [comment]
To be clear, that command was run by r10k?

**Comment by adrienthebo** [comment]
Oh, sorry, I didn't read your comment clearly enough. Thanks for confirming that, we should be able to get this PR merged shortly then!

**Comment by lmayorga1980** [comment]
@adrienthebo thanks!!

**Comment by lmayorga1980** [comment]
@adrienthebo planing to release a new gem version?

**Comment by adrienthebo** [comment]
@lmayorga1980 this will be released in r10k 2.1.0; we haven't yet determined when that release will go out but we'll keep you informed about that.

**Comment by adrienthebo** [comment]
Merged in 1e41180.

**Pull request merged**
