### PR TITLE
Make Digest subclass lookup thread-save

### LINKED ISSUE #979: Bug: Digest::Base cannot be directly inherited in Ruby
## Describe the Bug
r10k sometimes throws an `Digest::Base cannot be directly inherited in Ruby` error. This leads to module not being deployed and therefore other errors (failing CI pipelines in our case).

This showed up after we enabled the `pool_size` feature. (Currently using `pool_size: 10`)

## Expected Behavior
r10k doesn't fail and successfully deploys all modules.

## Steps to Reproduce
Currently I can't reliably reproduce this. We had 6 (out of probably thousands) jobs failing with this error within ~24h.

## Environment
 - Ruby: 2.5.3
 - r10k Version: 3.3.1
 - Platform: Debian 9.8 running in a docker container onto of a OpenStack VM.

### PR DESCRIPTION
**Pull request by baurmatt**
Fixes #979.

### CODE REVIEW

**Review by Magisus — APPROVED** [review]
Good catch!

**Comment by Magisus** [comment]
From notes I found, this will be effective in Ruby >= 2.2. At this point r10k requires 2.3, so sounds like we're good.

**Comment by baurmatt** [comment]
Wow that was fast! Thanks a lot @Magisus! :) Any chance we can get this bug fix in a new Rubygem release? ;)

**Comment by Magisus** [comment]
This is actually causing a problem in our FIPS-compliant builds, so I want to see if I can get that sorted before I release this. But hopefully soon!

**Comment by baurmatt** [comment]
Oh, if I can help fixing the problem, let me know! :)

**Comment by Magisus** [comment]
Finally got the bottom of our issues, and it turns out they were unrelated to this PR! I'll get this released.

**Pull request merged**
