### PR TITLE
Changed profile/base path, flag 'p' to mkdir, mod stdlib

### PR DESCRIPTION
**Pull request by guzmanbraso**
Fixes on this commit:
- Changed profile/base path to work with given modulepath.
- Added flag 'p' to mkdir to avoid error when creating directories under non existant directories.
- Added module stdlib to example Puppetfile because ntp need it to use str2bool().

### CODE REVIEW

**Comment by guzmanbraso** [comment]
Issue #175

**Comment by ghost** [comment]
Looks like some Travis CI issue causing the failure above. Otherwise :+1:

**Comment by guzmanbraso** [comment]
No problem, the travis issues seems external to this commit, hanged on rvm --version.

I've another commit waiting for this pull to be accepted on my fork to make quickstart work on Debian 7 besides Centos.

**Comment by adrienthebo** [comment]
Thanks very much!

**Pull request merged**
