### PR TITLE
lock cri gem version

### PR DESCRIPTION
**Pull request by aerickson**
see https://github.com/puppetlabs/r10k/issues/930

### CODE REVIEW

**Comment by aerickson** [comment]
Regarding the test failures, I believe they would fail on master if rerun (I can't seem to trigger a run).

The cri gem was updated last night and the last master build was before then.

**Review by justinstoller — APPROVED** [review]

**Comment by justinstoller** [comment]
@Iristyle 	@underscorgan 	Do you understand why the docker tests are failing here? I don't see how this is related to the PR in question.

**Comment by underscorgan** [comment]
so the conversation doesn't only exist in slack, this is failing since we're installing from gem not building from source. Have added a card to look into only running the tests when changes happen in the 'docker' directory.

**Comment by aerickson** [comment]
@underscorgan Thanks for the clarification.

**Comment by smortex** [comment]
The problem is fixed in [cri-2.15.8](https://github.com/ddfreyne/cri/pull/100).

**Pull request merged**
