### PR TITLE
Adding a flag to overwrite the locally changed modules

### PR DESCRIPTION
**Pull request by netdata-be**

### CODE REVIEW

**Comment by fatmcgav** [comment]
Would be good to get this supported, as I'm hitting issues with spurious local modifications... 

@netdata Any chance you can rebase? Suspect will need some tests aswell...

**Comment by netdata-be** [comment]
@fatmcgav Rebased and added spec tests, hope it gets accepted

**Comment by andersonmills** [comment]
This is referenced in https://tickets.puppetlabs.com/browse/RK-264

**Comment by andersonmills** [comment]
@netdata Hey, I know it's been forever on this (priorities), but would you be willing to rebase on 2.5.x. I think I would accept this as-is. (D'oh, that'll have to be a separate PR since it'd be merging to a different branch. Willing?)

**Comment by andersonmills** [comment]
@netdata - I made a new PR with your code .. #772

**Comment by gdubicki** [comment]
This MR should be closed now that it's successor, #772 , is merged.

**Pull request closed without merging**
