### PR TITLE
Use the SPDX format in the license

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by adrienthebo** [comment]
What is SPDX?

**Comment by tampakrap** [comment]
http://spdx.org/licenses/

**Comment by adrienthebo** [comment]
Could you update the commit message to reference this link and indicate that this is being done for the sake of OpenSUSE packages?

**Comment by tampakrap** [comment]
done

**Comment by adrienthebo** [comment]
Thanks for the contribution! Do you need a 1.3.6 release so that you can ship this out on your end? And if so do you need any other changes made for packaging?

**Comment by tampakrap** [comment]
The followings are still pending:
1) a change in gemspec git ls-files, to exclude a few dot files to make rpmlint happy. I'll submit a pull request for this shortly
2) cri ~> 2.6 (https://github.com/adrienthebo/r10k/pull/226)
3) multi_json ~> 1.10
4) faraday ~> 0.9

I haven't checked at all yet in the code if the updates in the deps are possible without any changes in r10k

**Pull request merged**
