### PR TITLE
(maint) puppet_forge: Allow 3.x & fast_gettext/gettext: Allow newer gem versions

### PR DESCRIPTION
**Pull request by bastelfreak**
Please add all notable changes to the "Unreleased" section of the CHANGELOG in the format:
```
- (JIRA ticket) Summary of changes. [Issue or PR #](link to issue or PR)
```

### CODE REVIEW

**Comment by Magisus** [comment]
Merged the thing removing Travis, if you wanna rebase this.

**Comment by bastelfreak** [comment]
@Magisus I rebased it

**Review by Magisus — COMMENTED** [review]
I tested this with both the agent's Ruby 2.5 and Ruby 3 locally, and it seemed to work correctly, in combination with https://github.com/puppetlabs/r10k/pull/1301.

I'm going to push that combination up in a new PR that also has a Ruby 3 GHA added, to just do more thorough testing.

**Comment by Magisus** [comment]
Superseded by https://github.com/puppetlabs/r10k/pull/1302

**Pull request closed without merging**
