### PR TITLE
(CPR-665) build r10k alpine image

### PR DESCRIPTION
**Pull request by underscorgan**
Build r10k alpine image including rugged gem. Does not include puppet or
puppet agent.

### CODE REVIEW

**Comment by underscorgan** [comment]
When looking at a ticket that came in regarding installing the rugged gem for use with r10k, I started looking at converting r10k to use alpine. I don't think this container actually needs puppet/puppet-agent for anything, I think it was just using that as a means of not using system ruby? What do y'alls think?

**Comment by nwolfe** [comment]
Awesome!

Seems like a good change.

Does this invalidate the need for #902 ?

**Comment by underscorgan** [comment]
@nwolfe yep, this would invalidate #902

**Comment by underscorgan** [comment]
I don't think there's more work here, mostly had this marked as a draft so we could make sure this seemed like a reasonable direction

**Pull request merged**
