### PR TITLE
Revert "Move deploy options into subcommands that actually support them" + Revert "Add R10K::CLI spec tests"

### PR DESCRIPTION
**Pull request by mwaggett**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by mwaggett** [comment]
hey @nabertrand ! We really appreciate your contribution to r10k, but this change caused the r10k CLI to no longer accept some options, notably `--cachedir`, which is causing issues in PE. We’re happy to work with you on any future contributions!

**Comment by nabertrand** [comment]
Hi @mwaggett! I tried to ensure that my changes didn't break anything, but apologies if I missed something. If you can provide an example usage that broke with this change, I might be able to fix it and add a spec test to make sure it doesn't break again in the future.

**Comment by nabertrand** [comment]
I opened #1048 to solve the issue I'm assuming this PR was created in response to. Let me know if there's anything else I can do.

**Comment by adrienthebo** [comment]
@mwaggett @nabertrand let's get tests passing on master, we can expand test coverage for the CLI in #1048.

**Review by adrienthebo — APPROVED** [review]

**Comment by nabertrand** [comment]
@adrienthebo if master is failing with just the one `R10K::CLI r10k Cri argument parsing when help specified prints command help and exits 0` test, that should be fixed in #1042, which I believe is ready for merge: https://github.com/puppetlabs/r10k/pull/1048#issuecomment-619118764

**Review by Magisus — APPROVED** [review]
So it sounds like we want to go forward with this revert for now, and re-add the tests a little differently later on, right?

**Comment by adrienthebo** [comment]
> So it sounds like we want to go forward with this revert for now, and re-add the tests a little differently later on, right?

That's my vote - I'd prefer that we build the test coverage incrementally and build tests on a per-option and per-command basis for simplicity.

**Pull request merged**
