### PR TITLE
(RK-236) Add git proxy settings support to r10k.yaml.

### PR DESCRIPTION
**Pull request by scotje**

### CODE REVIEW

**Comment by andersonmills** [comment]
Did you look at the docs directory to make sure all that's up to date with this?

**Comment by andersonmills** [comment]
I'm :+1: on everything up to 791c7f3 at this point.

**Comment by andersonmills** [comment]
LGTM :+1:

**Comment by scotje** [comment]
OK, going to squash the docs commit into the the proxy settings commit but leave the other two distinct.

**Comment by scotje** [comment]
Decided to wait for the RK-237, which will actually make the new settings effectual, before merging this.

**Pull request merged**
