### PR TITLE
(RK-222) Add :install_path option to non-Forge Puppetfile entries

### PR DESCRIPTION
**Pull request by scotje**
I'm going to get some unit tests added to this before merging, but there wasn't any existing test coverage so the tests should still be passing.

### CODE REVIEW

**Comment by andersonmills** [comment]
:+1: up to here. Waiting for tests for the whole thumb.

**Comment by scotje** [comment]
I should probably update the README and stuff as well...

**Comment by andersonmills** [comment]
:+1: I'm so happy! But even more happy to see the updated docs.

**Comment by andersonmills** [comment]
👍 Happy with the docs, too.

**Pull request merged**
