### PR TITLE
Add working --help option to deploy environment and deploy display

### PR DESCRIPTION
**Pull request by danieldreier**
running r10k deploy environment --help previously attempted to deploy rather than showing help
consequently, there was no documentation internally for the commonly-used -p option

### CODE REVIEW

**Comment by danieldreier** [comment]
Is there anything holding this up? I'm glad to make changes, take a different approach, whatever but as an amateur with r10k it'd be really nice to be able to use the --help flag with deploy environment. This seems like a simple enough fix.

**Comment by adrienthebo** [comment]
@danieldreier sorry, no, I've just been out with a cold and too medicated to get anywhere near a keyboard without wreaking havoc. Thanks for raising an issue about this, it's been a long standing issue but I haven't made an issue for it. I'll see about getting this turned around this evening. Thanks again for reporting it!

**Comment by danieldreier** [comment]
I'm perfectly glad to do the work, just thought I'd check in first and see if this particular approach is the right way. If so I can do the same elsewhere in r10k - I think I noticed a few other areas where help was missing.

**Comment by danieldreier** [comment]
latest commit switches to a help command (e.g. `r10k help deploy environment`) but will only work for subcommands if cri accepts my somewhat hacky pull request to enable that. 

I know you said you had another approach in mind - I just did this trying to figure out what the cri-standard approach to help is. No hard feelings if you close this out and do it another way.

**Comment by adrienthebo** [comment]
@danieldreier I'm working on getting 1.2.0 stabilized and released right now, so I'm going to hold off a few more days on this while I get that out. I'm going to target this at the 1.2.1 release. Thanks for your patience on this!

**Comment by danieldreier** [comment]
No rush. I appreciate the update.

**Comment by danieldreier** [comment]
FYI, CRI recently added support for help on subcommands (https://github.com/ddfreyne/cri/pull/27) and that change was released in CRI 2.5.0. I just tested, and this pull request works with the current r10k pull request and the released version of CRI 2.5.0. The gemspec file would need to be updated to reflect that dependency; I can add that to the pull request if you like. No rush, just wanted to let you know about the change in cri.

**Comment by adrienthebo** [comment]
Yeah, let's go ahead and bump the version on Cri to 2.5.0, and when you do that I'll merge it in. Thanks for catching that update!

**Comment by danieldreier** [comment]
Okay, updated r10k.gemspec to reflect the cri 2.5.0 dependency, and updated the readme to use the help subcommand rather than --help. 

The only minor remaining concern I have is that running r10k deploy environment --help still runs a deployment, but that seems like a separate issue. Let me know if you see any other changes needed to merge.

**Comment by adrienthebo** [comment]
@danieldreier let's definitely make sure that the deployment behavior with --help gets fixed before 1.2.1, but that can be a separate issue. Thanks for the work on this and your continued patience!

**Pull request merged**
