### PR TITLE
Add possiblity to send logs to syslog

### PR DESCRIPTION
**Pull request by johanfleury**
Hi folks.

This PR adds the possibility to send logs to syslog through a new command line argument.

This is a work in progress but its my first time writing ruby and the r10k codebase is quite big. I wanted to have your feedback before going further (especially unit tests).

What do you think?

### CODE REVIEW

**Comment by johanfleury** [comment]
My changes here won't be working with the log4r repository's master branch but only with their latest gem version.

To be fair, log4r doesn't seem to be a well maintained project. Their repository doesn't have any tags/release. and their latest available gem is 1.1.10 and was published in 2012.

**Comment by johanfleury** [comment]
Any updates on this PR ?

**Comment by johanfleury** [comment]
Any updates on this PR ?

**Comment by johanfleury** [comment]
This PR is more than 1 year old now, any updates?

**Comment by adrienthebo** [comment]
Hi @johanfleury, thanks for your patience on this! I'd like to get this pull request merged and I have a couple of suggestions, are you still interested in working on this?

**Comment by johanfleury** [comment]
Hey @adrienthebo, I’m glad this can finally move forward.

I don’t have a strong need on this feature anymore, but I’m still willing to work on this PR.

**Comment by binford2k** [comment]
@adrienthebo do you have time to provide feedback on this? Otherwise, I'm inclined to merge as is.

**Comment by mwaggett** [comment]
This doesn't have tests, so please don't merge as is.

@johanfleury I know you previously said you don't need this feature anymore, but are you _interested_ in working on this? If so, we're happy to help. Otherwise, I think we should close this.

**Pull request closed without merging**
