### PR TITLE
Merge main -> 4.x

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Comment by mwaggett** [comment]
hmm @davidsandilands I wonder if something got weird with your CLA after switching to using your Perforce email address - I'm wondering if you were using a different email address when you originally contributed (https://github.com/puppetlabs/r10k/pull/1315). Maybe it would work to add back your Puppet email as a secondary email address on your Github account?

**Comment by davidsandilands** [comment]
Hey @mwaggett I was using my Puppet one and changed I'll sort this

**Comment by mwaggett** [comment]
@davidsandilands Thanks! Let me know when it's done and I can re-run the CLA check.

**Comment by davidsandilands** [comment]
@mwaggett hopefully that should be it done wasn't thinking through removing old addresses

**Comment by mwaggett** [comment]
Looks like that worked, thanks @davidsandilands !

**Review by steveax — APPROVED** [review]
👍

**Pull request merged**
