### PR TITLE
Merge 3.2.x -> master

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by Magisus** [comment]
Last one for r10k. FWIW I have a ticket high on my backlog to add automation for these mergeups. But in the meantime, thanks for your help @chrisleicester following up on the initial merge!

**Review by chrisleicester — APPROVED** [review]
The changes I made all look good.

@Magisus is this something you'd like me to merge in as well? Or is this last one a special one. (though I'm just now seeing the tests have failed).

**Comment by Magisus** [comment]
I'm going to ask about the failing docker tests, sometimes the pupperware team has more insight into whether those failures are bad or not. /cc @nwolfe

**Comment by Magisus** [comment]
Got the thumbsup from Pupperware to ignore the docker failure for now. Feel free to merge @chrisleicester.

**Pull request merged**
