### PR TITLE
cli/puppetfile: add moduledir and puppetfile

### PR DESCRIPTION
**Pull request by rowleyaj**
These options appear to already be handled by the action.
Surfacing them at the command level so they can be used

### CODE REVIEW

**Comment by rowleyaj** [comment]
@adrienthebo is anything else required from me to pose this for review? It looked like it was a wanted change as there was todo items in the code for it. I think the deprecated part was pulling this settings from env vars, but I may have misunderstood and the functionality as a whole was deprecated.

**Comment by adrienthebo** [comment]
@rowleyaj sorry for the delay - this looks good, and I should be able to merge this as-is and just got bogged down. With luck I'll be able to get to it shortly. Again, sorry for the delay and thanks for both the contribution and your patience!

**Comment by adrienthebo** [comment]
Merged into master in 221c7df; this should be released in 2.1.0. Thanks for the contribution!

**Comment by rowleyaj** [comment]
Thanks @adrienthebo :)

**Pull request merged**
