### PR TITLE
(CODEMGMT-104) Update Tests to Use Acceptance Forge

### PR DESCRIPTION
**Pull request by cowofevil**
Currently we run our tests against production Forge which could present problems
with test stability. All Beaker configs have been updated to reference the
acceptance forge. All tests that use modules from the Forge have been updated
to use the "stub_forge_on" function.

### CODE REVIEW

**Comment by cowofevil** [comment]
@carlosvelarde I found a lot of errors in the tests that were causing a variety of failures. I fixed them all up and this PR is ready for review again.

**Comment by cowofevil** [comment]
@carlosvelarde I have updated the PR again to finally fix all the brokeness! You will need to force pull this branch because I did a rebase on master. The reason things started breaking was because of changes in the "stdlib" Forge module. I also needed to prevent a test from running on anything but the EL platforms.

**Comment by cowofevil** [comment]
@carlosvelarde Okay, I ran all the tests against all platforms and they passed. Please review again.

**Comment by carlosvelarde** [comment]
Only test that fails is neg_duplicate_module_names.rb with a network failure to https://forgeapi.puppetlabs.com. Passes when I run it solo.

**Pull request merged**
