### PR TITLE
(RK-288) Catch NameErrors while parsing Puppetfiles

### PR DESCRIPTION
**Pull request by ajroetker**

### CODE REVIEW

**Comment by ajroetker** [comment]
@haus @andersonmills tests are passing it's oddly trying to grab from the wrong remote on the push hook though

**Comment by haus** [comment]
weird.

**Review by haus — APPROVED** [review]
winking

**Comment by andersonmills** [comment]
Well, it's something, and now there's a test. Here's the new...
```
roquefort:~/puppet/src/r10k (PR720)
$ be r10k puppetfile check
Failed to evaluate /Users/anderson/puppet/src/r10k/Puppetfile
Original exception:
undefined method `to_ary' for "andersonmills/happiness":String
```

Here's the old...
```
roquefort:~/puppet/src/r10k (master)
$ be r10k puppetfile check
undefined method `to_ary' for "andersonmills/happiness":String
```

**Review by andersonmills — APPROVED** [review]

**Comment by andersonmills** [comment]
I'm not sure what Travis was doing there, but it's looking for your branch name @ajroetker in the puppetlabs repo. Not sure why.

This looks like correct (trying to pull the branch directly from the puppetlabs repo), but I still don't get it. Lots of cases online where one fails for apparent infrastructure reasons and the other doesn't.

**Comment by andersonmills** [comment]
yes

**Pull request merged**
